apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.0 # O la versión que estés usando
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        resources: # <--- AÑADE ESTA SECCIÓN
          requests:
            memory: "64Mi"  # Solicita 64 Megabytes de RAM
            cpu: "100m"     # Solicita 0.1 CPU (m = millicores)
          limits:
            memory: "128Mi" # Límite de 128 Megabytes de RAM
            cpu: "250m"     # Límite de 0.25 CPU
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index-html